name: trainee_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 
  dio: ^5.4.3+1 
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10 
  json_serializable: ^6.8.0 

 

flutter:
  uses-material-design: true
